Frontend:
  impl: ReadWriteTrace
  clock_ratio: 8
  num_expected_insts: 500000
  path: example_inst.trace

  Translation:
    impl: NoTranslation
    max_addr: 1073741824
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: DDR4
    org:
      preset: DDR4_8Gb_x8
      channel: 1
      rank: 1
    timing:
      preset: DDR4_4000

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: ClosedRowPolicy
      cap: 4
    plugins:

  AddrMapper:
    impl: ChRaBaRoCo
